# Generated by Django 2.2.7 on 2019-12-21 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_text', models.TextField(max_length=200)),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('visibility_mode', models.CharField(choices=[('PUB', 'Public'), ('PRVT', 'Private'), ('FRND', 'Friends')], default='PUB', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='who_posted', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
