# Generated by Django 2.2.7 on 2019-12-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_album_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='visibility_mode',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('Friends', 'Friends')], default='Public', max_length=10),
        ),
    ]
