# Generated by Django 2.2.7 on 2019-12-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
    ]
